# looking ahead 

In class, we discussed this assignment yesterday. In the following weeks, start looking for what you will want to spend your extra time on this semester.

Try, for yourself, to answer the following questions:

- Where do I want to be in ~2 years time?
- dont want to work in the lab my whole life so i choose to learn data science. Later in life i want to become a the head of the lab and work a more communication like job. This is where the datascience comes in handy. The skills I acquired will be usefull for me to make a good visualisation of the data and allow me to communicate this way with the lab 
In two years i want to be working


How am I doing now with respect to this goal?


What would be the next skill to learn?
Making dashboards with R shiny
Make a planning on how to start learning this new skill.
- start with an introduction to R shiny.
- make a basic shiny dashboard
- try to make a shiny dashboard with the data i collected. (antibiotic usage)
-- make it interactive so you can choose the type of anticiotics, and maybe show a map of each county with the percentage of defined daily dose (DDD).

Note the following points:

It has to be life sciences or useful for life sciences (no knitting, riding horses etc)
It has to be data science / bioinformatics
You have to show your plan in your portfolio, together with the result of the first few steps you took in trying to reach this goal.
You probably won’t learn this skill in a few days. Just get started.
This assignment will show us whether you succeeded in reaching an overview of the field and possibilities in data science for biology.